services:
  supsvc:
    # build:
    #   context: .
    image: ghcr.io/tofoli/supervise:main
    container_name: supervise
    restart: unless-stopped
    privileged: true
    ports:
      - 4470:4470
    devices:
      - /dev/bus/usb:/dev/bus/usb
